- name: Variables through tasks
  hosts: local
  connection: local
  var:
    COURSE: DevOps
    Duration: 24HRS
    TRAINER: Siva

  tasks:
    - name: Print the Course info
      var: 
        COURSE: Ansible

      ansible.builtin.debug:
          msg: "The Course name is {{ COURSE }}, {{ DURATION }}, {{ TRAINER }}"
