- name: Varaibles from files
  hosts: local
  connection: local
  vars_files: 
  - course.yaml
  tasks:
    - name: Print course info
      ansible.builtin.debug:
        msg: "Course name is: {{ COURSE}} {{ DURATION }} {{ TRAINER }}"
