- name: data types
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120
    is_live: true
    tools: #["Linux", "Shell", "Ansible"]
    - "Linux"
    - "Shell"
    - "Ansible"
    concept: #dictionary or map
      cloud: AWS
      CM: Ansible
  tasks:
  - name: Print Course info
    ansible.builtin.debug:
      msg: "Course Name: {{ COURSE }}, Duration is: {{ DURATION }}, is it live?: {{ is_live }}, tools are {{ tools }}, concepts are: {{ concepts }}"
