- name: Functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Linux, AWS, Shell, Ansible
    
    tags: 
      Application: payment
      Environment: dev

    listtags:
    - key: Application
      value: payment
    - key: Environment
      value: dev

  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('ABC') }}" 

  - name: convert string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "Tag map: {{ listtags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
        file_yaml: "{{ lookup('file', 'file.yaml') | from_yaml }}"

  - name: convert yaml into jason
    ansible.builtin.debug:
        msg: "json: {{ file_yaml | to_json }}"